GoldenOwlAsia/goldenowl.asia

src/components/SubHeaderServices/index.js, src/components/SubHeaderServices/index.sass
- Task: https://trello.com/c/zd6uX3TS/186-the-submenu-works-quite-weird
=> fix - dropdown menu

src/components/Footer/index.js, src/components/Mission/index.js, src/components/Mission/index.sass, src/components/ServicesDescription/index.js, src/components/ServicesDescription/index.sass, src/components/ServicesDetail/index.js, src/components/ServicesDetail/index.sass, src/components/SubHeader/index.js, src/components/SubHeader/index.sass, src/components/SubHeaderServices/index.js, src/components/SubHeaderServices/index.sass, src/pages/WebDevelopment/index.sass, src/styles/mixins.sass, src/utils/ServicesDetail.js
- Task: 
+ https://trello.com/c/zd6uX3TS/186-the-submenu-works-quite-weird
+ Add links for footer
+ Add links for service
=> Fix bugs ui

src/components/Tabs/TabContent.js, src/components/Tabs/TabHeader.js, src/components/Tabs/Tabs.js, src/components/Tabs/index.js, src/components/Tabs/index.sass
- Task: Add active tab for technologies tab
- Screenshot:
=> Active tab

src/pages/Services/components/ServicesDescription/index.js, src/pages/Services/components/ServicesDescription/index.sass
https://trello.com/c/ZkP6ezyn/258-services
=> fix UI: Services

src/pages/Blog/index.sass
- change blog title font-family (https://trello.com/c/oYpm9fxf/266-blog-page)
=> fix UI: Blogs

src/components/Footer/index.js, src/components/Tabs/TechTabs.js, src/components/Tabs/index.sass, src/pages/Technology/components/Guarantee/index.js, src/pages/Technology/components/Guarantee/index.sass, src/pages/Technology/components/TechnologyCards/index.sass, src/pages/Technology/components/TechnologyDetail/index.js
- fix wrong technology typos and styles (https://trello.com/c/W1nPJ0Lx/264-technology)
=> fix: Technology

src/pages/Testimonials/components/RunningPanels/index.js, src/pages/Testimonials/components/RunningPanels/index.sass, src/pages/Testimonials/components/TestimonialsList/index.sass
- fix testimonials title font family
- replace gray row with logo row
=> fix UI: testimonials

src/components/Contact/index.sass, src/components/Explore/index.sass, src/components/Footer/index.js, src/components/Footer/index.sass, src/components/MainHeader/index.js, src/components/MainHeader/index.sass, src/components/Partners/index.sass, src/components/ScrollToTop/index.js, src/components/SubHeader/index.js, src/components/SubHeader/index.sass, src/components/SubHeader/service.sass, src/pages/App/index.js, src/pages/App/index.sass, src/pages/Home/components/CompanyQualities/index.js, src/pages/Home/components/CompanyQualities/index.sass, src/pages/Home/components/Introduction/index.js, src/pages/Home/components/Introduction/index.sass, src/pages/Home/components/Mission/index.sass, src/pages/Home/components/Quote/index.sass, src/pages/Home/components/Technologies/index.sass, src/styles/variables.sass
https://trello.com/c/iNMBOmUv/256-home-page
=> Fix UI: Home and general section

src/components/Tabs/TechTabs.js, src/components/Tabs/index.sass, src/pages/Technology/components/Guarantee/index.js, src/pages/Technology/components/Guarantee/index.sass, src/pages/Technology/components/TechnologyCards/index.sass, src/pages/Technology/components/TechnologyDescription/index.js, src/pages/Technology/components/TechnologyDescription/index.sass, src/pages/Technology/components/TechnologyDetail/index.js, src/pages/Technology/components/TechnologyDetail/index.sass
- apply mixins 
- mobile responsive for Technology Page
=> UI: Technology mobile responsive

src/pages/App/index.sass, src/pages/Contact/index.js, src/pages/Contact/index.sass
- apply mixins 
- mobile responsive for Contact page
=> UI: Contact mobile responsive

src/components/PortfolioHeader/index.js, src/components/PortfolioHeader/index.sass, src/components/PortfolioInteresting/index.sass, src/pages/PortfolioSubPage/index.js, src/pages/PortfolioSubPage/index.sass, src/utils/portfolioDetails.js
- apply mixins 
- mobile responsive for Portfolio Project pages
=> UI: Portfolio project pages mobile responsive

src/components/AutoCarousel/index.sass, src/components/Contact/index.sass, src/pages/About/components/Develop/index.sass, src/pages/App/index.sass, src/pages/Blog/index.js, src/pages/Blog/index.sass, src/pages/Contact/index.js, src/pages/Contact/index.sass, src/pages/Home/components/CompanyQualities/index.sass, src/pages/Services/components/ServicesDescription/index.js, src/pages/Technology/components/Guarantee/index.js, src/pages/Technology/components/Guarantee/index.sass, src/pages/Technology/components/TechnologyCards/index.sass
- Font scale: Contact, Blog
- Fix mobile responsive bugs (trello card 283, 285, 346, 347, 348, 349)
=> Contact and Blog font scale + fix mobile responsive UI bugs

src/pages/Home/components/Archieves/index.js
when user scroll to position component number, animation is  starting
=> fixed scroll animate number

src/components/BlogHeader/index.js, src/utils/singleServiceDetails.js
can not route to home page when user click logo company ( mobile an desktop)
=> fixed router blog page

server/index.js, server/server.js, server/sitemap-builder.js, src/pages/Testimonials/components/RunningPanels/index.js, src/pages/Testimonials/components/RunningPanels/index.sass
=> Fix on refresh testimonial page bug

server/index.js, src/index.js, src/pages/PortfolioSubPage/index.js
- Reason: Can't load porfolio project page with next project link from for loop
- Solution: use Array.filter instead of for loop
=> Fix: Portfolio next project

server/server.js, server/sitemap/routes.js, src/api/blogs.js, src/api/careers.js, src/pages/Blog/index.js, src/pages/Blog/index.sass, src/pages/BlogDetails/index.js, src/pages/BlogDetails/index.sass, src/pages/Career/index.js, src/pages/CareerDetails/index.js, src/routes/index.js
- Update on blog's and career's urls
- Reorder jobs list by status value
=> Update: use slug instead of id for urls

server/server.js, src/pages/Blog/index.js, src/pages/BlogDetails/components/RelatedBlog/index.js, src/pages/BlogDetails/components/RelatedBlog/index.sass, src/pages/BlogDetails/index.js, src/pages/BlogDetails/index.sass
=> Feature: related blogs

src/components/Footer/index.js, src/components/MainHeader/MobileMenu.js, src/components/MainHeader/index.js, src/pages/BlogDetails/index.js, src/pages/BlogDetails/index.sass, src/pages/FAQ/components/Cross/index.js, src/pages/FAQ/components/FAQPanels/index.js, src/pages/FAQ/components/Plus/index.js, src/pages/FAQ/index.js, src/pages/FAQ/index.sass, src/pages/Portfolio/index.js, src/utils/faqData.js
- Update - Blog details: remove blog source and handle image's responsive
- Update FAQ: remove line breaks
- Update Website: use html attributes to open pages in new tab instead of js
- Fix: FAQ item UI bug and svg iOS bug - can't use rotate
=> Update: FAQ UI and content

package.json, src/pages/Home/components/CompanyQualities/index.js, src/pages/Home/components/CompanyQualities/index.sass, src/pages/Home/components/IntroVideo/index.js, src/pages/Home/components/IntroVideo/index.sass, src/pages/Home/index.js
=> Fix align text and add video into homepage

src/pages/PortfolioSubPage/index.js
- Change headings text portfolio
=> change headings text portfolio

public/home-amp.html
Add blog link to the home page when viewing by mobile on AMP mode
=> fix/edit UI

src/utils/feedback.js, src/utils/testimonials.js
=> Fix spelling mistake

src/pages/Home/components/OurArchievements/index.js, src/pages/Home/components/OurArchievements/index.sass, src/pages/Home/index.js
=> add badges
